### ISSUE TITLE
not compatible with JDK 10

### ISSUE THREAD

**Issue by Mazen-Embaby** [Jerady/fontawesomefx-glyphsbrowser#11]
Compatibility issue:
It works fine in JDK 1.8 but when run in JDK 10 this error shown 

Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/parser/CSSParser
	at de.jensd.fx.glyphs.GlyphIcon.<clinit>(GlyphIcon.java:48)
	at de.jensd.fx.glyphs.browser.GlyphsBrowserAppModel.lambda$init$0(GlyphsBrowserAppModel.java:92)

**Comment by veyselsari23** [comment]
Yes , when install jdk 10 then .jar file not turn on , please help for this issue. Thanks

**Comment by davesrambla0123** [comment]
I used JDK 10 and when i run the jar file of fontawesomefx-glyphsbrowser. I can't see anything!

**Comment by rruipinheiro** [comment]
Same issue... Please help, thanks

**Comment by davesrambla0123** [comment]
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/parser/CSSParser
	at de.jensd.fx.glyphs.GlyphIcon.<clinit>(GlyphIcon.java:48)
	at de.jensd.fx.glyphs.browser.GlyphsBrowserAppModel.lambda$0(GlyphsBrowserAppModel.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at de.jensd.fx.glyphs.browser.GlyphsBrowserAppModel.init(GlyphsBrowserAppModel.java:93)
	at de.jensd.fx.glyphs.browser.GlyphsBrowserAppModel.<init>(GlyphsBrowserAppModel.java:85)
	at de.jensd.fx.glyphs.browser.GlyphsBrowserApp.start(GlyphsBrowserApp.java:41)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.parser.CSSParser
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more
Exception running application de.jensd.fx.glyphs.browser.GlyphsBrowserApp

**Comment by davesrambla0123** [comment]
Can someone gives me solution for this?

**Comment by rruipinheiro** [comment]
@davesrambla0123 Which version of java jdk do you use ?

**Comment by veyselsari23** [comment]
Java jdk 10

**Comment by goxr3plus** [comment]
It has to do with the dependencies of the library. It is using 'controlsfx 8' which is not compatible with Java 10. Once upon a time i pull requested the search bar feature. It seems that i have to fix this too when i have time :)

**Comment by devs-byte** [comment]
haven't they released yet : (

**Comment by goxr3plus** [comment]
@J-Java You want it badly :)? You can use IKONLI FONT icons, far better in my humble opinion and more supported :)

**Comment by SkaaRJik** [comment]
Install 1.8.  - JDK 10 is not supporting JavaFX...
